
version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout # I checkout the repo here, but this would be handled by the taskfile called in the circlci config
      - run:
          name: "Say hello"
          command: | # Based on the taskfile looks like the repo is cloned into /tmp folder so I'm just simulating that here.
            echo "Cloning timestamp repo. Hello, World!"
            mkdir -p workspace/deep/inside/folder
            cp app.py workspace/deep/inside/folder/app.py
            touch workspace/deep/inside/folder/test.csv
            echo "This is my test csv" > workspace/deep/inside/folder/test.csv
      - persist_to_workspace:
          root: . # relative to workspace
          paths:
            - "workspace/deep/inside/folder/test.csv" # relative to root path
            - "workspace/deep/inside/folder/app.py" # relative to root path

  say-hello-again:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: . # relative location to mount the persisted workspace 
      - run:
          name: Use Persisted File
          command: | # just some sample code to show that the file is persisted and can be used
            echo "Accessing the persisted app.py from the workspace and printing it out"
            ls -latr workspace
            cat workspace/app.py
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-hello-again:
          requires: # probably a good idea to make sure the first job is successful before running the one which needs the file from cloned repo
            - say-hello
